### ISSUE TITLE
Gamepad behaviour is incorrect

### ISSUE THREAD

**Issue by grabmateusz** [virtual-programming/dirtshowdown-linux#8]
Hi guys,
I would like to report issue that occurs in DIRT Showdown and one that is a general eon issue that is the same for other ports (in my case it happens in Spec Ops: the Line, but I think it did not occur in the Witcher 2).

First of all I use Dualshock 4.

When race starts very often gamepad does not respond for right trigger - I have to release it and press it again - than it works. It's annoying and it would be very good if this issue is fixed.

What's more - When entering the game it behaves like gamepad is incorrectly calibrated.
There is a known workaround by doing circle with sticks, but this is not a solution to the problem, it is just workaround.

Here is my system information:

    Processor Information:
        Vendor:  GenuineIntel
        CPU Family:  0x6
        CPU Model:  0x2a
        CPU Stepping:  0x7
        CPU Type:  0x0
        Speed:  2900 Mhz
        4 logical processors
        2 physical processors
        HyperThreading:  Supported
        FCMOV:  Supported
        SSE2:  Supported
        SSE3:  Supported
        SSSE3:  Supported
        SSE4a:  Unsupported
        SSE41:  Supported
        SSE42:  Supported
        
    Network Information:
        Network Speed:  
        
    Operating System Version:
        Ubuntu 15.04 (64 bit)
        Kernel Name:  Linux
        Kernel Version:  3.19.0-25-generic
        X Server Vendor:  The X.Org Foundation
        X Server Release:  11701000
        X Window Manager:  Compiz
        Steam Runtime Version:  steam-runtime-release_2015-06-12
        
    Video Card:
        Driver:  NVIDIA Corporation GeForce GT 540M/PCIe/SSE2
    
        Driver Version:  4.5.0 NVIDIA 352.30
        OpenGL Version: 4.5
        Desktop Color Depth: 24 bits per pixel
        Monitor Refresh Rate: 60 Hz
        VendorID:  0x10de
        DeviceID:  0xdf4
        Number of Monitors:  1
        Number of Logical Video Cards:  2
        Primary Display Resolution:  1600 x 900
        Desktop Resolution: 1600 x 900
        Primary Display Size: 15,04" x 8,43"  (17,20" diag)
                                                38,2cm x 21,4cm  (43,7cm diag)
        Primary Bus: PCI Express 16x
        Primary VRAM: 1024 MB
        Supported MSAA Modes:  2x 4x 8x 16x 
        
    Sound card:
        Audio device: Intel CougarPoint HDMI
        
    Memory:
        RAM:  9910 Mb
        
    Miscellaneous:
        UI Language:  English
        LANG:  pl_PL.UTF-8
        Microphone:  Not set
        Total Hard Disk Space Available:  100662 Mb
        Largest Free Hard Disk Block:  14982 Mb
        
    Installed software:
        
    Recent Failure Reports:

**Comment by slackerbob** [comment]
The same thing is happening for me with an XBox 360 wireless controller

I just do a full circle with both sticks and do a full cycle press->release of both triggers while the game is loading up, otherwise the menu goes nuts (like I'm pressing directions)

My specs:

    Processor Information:
        Vendor:  GenuineIntel
        CPU Family:  0x6
        CPU Model:  0x1a
        CPU Stepping:  0x5
        CPU Type:  0x0
        Speed:  2661 Mhz
        8 logical processors
        4 physical processors
        HyperThreading:  Supported
        FCMOV:  Supported
        SSE2:  Supported
        SSE3:  Supported
        SSSE3:  Supported
        SSE4a:  Unsupported
        SSE41:  Supported
        SSE42:  Supported
        
    Network Information:
        Network Speed:  
        
    Operating System Version:
        Ubuntu 15.04 (64 bit)
        Kernel Name:  Linux
        Kernel Version:  3.19.0-26-generic
        X Server Vendor:  The X.Org Foundation
        X Server Release:  11701000
        X Window Manager:  Xfwm4
        Steam Runtime Version:  steam-runtime-release_2015-06-12
        
    Video Card:
        Driver:  NVIDIA Corporation GeForce GTX 570/PCIe/SSE2

        Driver Version:  4.5.0 NVIDIA 355.06
        OpenGL Version: 4.5
        Desktop Color Depth: 24 bits per pixel
        Monitor Refresh Rate: 59 Hz
        VendorID:  0x10de
        DeviceID:  0x1086
        Number of Monitors:  2
        Number of Logical Video Cards:  1
        Primary Display Resolution:  1920 x 1200
        Desktop Resolution: 3600 x 1200
        Primary Display Size: 22.91" x 14.33"  (27.01" diag)
                                                58.2cm x 36.4cm  (68.6cm diag)
        Primary Bus: PCI Express 16x
        Primary VRAM: 2560 MB
        Supported MSAA Modes:  2x 4x 8x 16x 
        
    Sound card:
        Audio device: Realtek ALC889
        
    Memory:
        RAM:  16035 Mb
        
    Miscellaneous:
        UI Language:  English
        LANG:  en_US.UTF-8
        Microphone:  Not set
        Total Hard Disk Space Available:  112546 Mb
        Largest Free Hard Disk Block:  41995 Mb
        
    Installed software:
        
    Recent Failure Reports:

**Comment by vpltd-kgalaj** [comment]
Essentially, currently our gamepad code doesn't trust the information about maximal, minimal and deadzone values from gamepad drivers, as we came across some drivers that reported incorrect values, which caused the gamepad controls to make the game unplayable (for example, cars turning to the right unless stick was kept all the way to the left, and unable to steer left at all ).

However, as the majority of gamers don't have these issues, starting from next update the game will be capable of operating in two modes: default one, where it does trust these values, and thus calibrating of gamepads you described will become unnecessary, and "do not trust" mode, which will be possible to enabled with "--eon_calibrate_gamepads" command-line option, in which it will only work with the current gamepad control values, and derive minimal, maximal and neutral values from these.

I expect the default mode will resolve this issue for you, and the "do not trust" mode will be a fallback for gamers for whom the default mode will produce broken steering.

**Comment by grabmateusz** [comment]
Hi @vpltd-kgalaj, for me proposed solution sounds like a great approach. Looking forward for the update.

**Comment by liamdawe** [comment]
That sounds like much nicer behaviour, leave it up to drivers that do work to work right away, ones that misbehave have another option. I repeatedly have to tell people the trick of rotating sticks and stuff for VP ports, and it will be nice to not have to for 99% of the cases.

**Comment by grabmateusz** [comment]
One last question regarding this topic - will this fix be applied to other titles as well?

**Comment by vpltd-kgalaj** [comment]
I expect it will, though gradually, as updates are released. In some cases we can't update the title freely. Also, it needs to be tested first - as usual, it seems there's nothing that could go wrong with this change, and something likely will.

**Comment by vpltd-peterm** [comment]
Please check this with the latest update, BuildID 757342

**Comment by ProfessorKaos64** [comment]
I will test with Xbox 360 (official) wired/wireless tonight. I can test PS3/PS4 if I get time, since my test machine for SteamOS is getting a fresh install tonight.

**Comment by grabmateusz** [comment]
It is the same for the Dualshock 4 (PS4 controller). Analog sticks are correctly calibrated on start, but trigger buttons (L2 and R2 buttons) do not work at all. Running game with --eon_callibrate_gamepads restores the previous behavior of the gamepad.

**Comment by liamdawe** [comment]
Logitech f310 working fine on latest patch, no weirdness :)

**Comment by stqn1** [comment]
Now I don’t have to pre-press all the buttons on my Dualshock 2 gamepad, but the bottom triggers don’t work anymore. I had to remap the acceleration and brake to the upper triggers.

**Comment by ProfessorKaos64** [comment]
I no longer have the wild scrolling on the menu, however I now get this behaviour in SteamOS brewmaster / 2.0:

1. Start game from default BPM interface
2. Hit A throw intros fine
3. Select create new profile (where can we delete these, now I have 4 haha).
4. Select create new autosave
5. Click player 1 box to enter name
6. Both the standard keyboard/daisy wheel entry methods that overlay are not in focus. Any input presses to not move around the onscreen keyboard.

So it seems, at least under SteamOS, that there are still some odd bugs in gamepad usage when creating a profile.

**Comment by vpltd-kgalaj** [comment]
As for gamepad controls not working on well known gamepads, we'll add more logging under --eon_log_gamepads option shortly, to try to get to the bottom of this once and for all without having to buy every gamepad model in existence.

As for SteamOS and generally Steam Big Picture behaviour, we're looking into it.

**Comment by ProfessorKaos64** [comment]
Thank you @vpltd-kgalaj . As for gampad support, at least supported the most common controller, the one I have, would be ideal. I would think testing under Xbox360 / PS3 controllers would be at least key. Thank you for your work.

**Comment by grabmateusz** [comment]
I would add PS4 controller to this list :)

2015-09-02 12:52 GMT+02:00 mikeyd <notifications@github.com>:

> Thank you @vpltd-kgalaj <https://github.com/vpltd-kgalaj> . As for gampad
> support, at least supported the most common controller, the one I have,
> would be ideal. I would think testing under Xbox360 / PS3 controllers would
> be at least key. Thank you for your work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/virtual-programming/dirtshowdown-linux/issues/8#issuecomment-137028347>
> .
>



-- 
Pozdrawiam,
Mateusz Grab

**Comment by stqn1** [comment]
As far as I know, using SDL2’s game controller API would solve the issue for all gamepads once and for all, at least when the games are run with Steam.

**Comment by ProfessorKaos64** [comment]
True, Valve uses SDL2 for their BPM interface remapping tool. The problem at times, is differing approaches in different operating systems (like xinput), middleware engines (e.g. Unity), or other native engines and tools.

**Comment by vpltd-peterm** [comment]
Our code is compatible with SDL2 gamepad mappings, and supports Steam controller mappings being sent to it. For various reasons, we are planning to move away from SDL2, and the gamepad code is the start of this. It also allows us to unify a lot of things with the Mac version of eON.

**Comment by vpltd-peterm** [comment]
OK, we've found that we have a problem parsing the SDLGamepad.config file, and this means some of the mappings in it are being ignored. The game then falls back to an in-built mapping for the PS4 pad, which has the left/right triggers defined as buttons rather than axes.

As a temporary workaround for this, you can specify the command line option --eon_gamepad_mapping="\<mapping string\>" to manually tell eON about a gamepad mapping. For PS4 pads, we have found the following works:
```
030000004c050000c405000011010000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,platform:Linux,
```

**Comment by vpltd-kgalaj** [comment]
Or you can probably just define the gamepad configuration in Steam Big Picture.

**Comment by grabmateusz** [comment]
In my case having Dualshock 4 connected with bluetooth and having launch options set to:

    --eon_gamepad_mapping="030000004c050000c405000011010000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,platform:Linux,"

did not solve the issue with left and right trigger being not responsive.

**Comment by vpltd-peterm** [comment]
If you are using it via Bluetooth, this will have a different UUID. 
Can you advise if the PS4 pad via Bluetooth works if you launch through Steam Big Picture mode?

**Comment by vpltd-peterm** [comment]
Please see the front page release notes for BuildID 761021, released today for more information

**Comment by ProfessorKaos64** [comment]
Will do, thank you @vpltd-peterm . By frontpage, do you mean the store announcement page for the game?

**Comment by vpltd-kgalaj** [comment]
I think he meant the front page of this Github.

This release also includes a lot more logging for --eon_log_gamepads option. If you find your gamepad still not working correctly with it, please launch the game with this option, press controls that don't work correctly a few times, quit game, compress eon.txt file and put it in this ticket in the usual way, along with some information of what's wrong. I hope this time it'll be enough logging to let me pinpoint the issue down to the line of code.

**Comment by ProfessorKaos64** [comment]
Excellent, thank you very much. I'll do some testing tonight on SteamOS.

**Comment by stqn1** [comment]
Left and right triggers still don’t work for me. My PS2 gamepad has been configured in BPM.

I don’t see any way to attach a file here, so here’s my log: http://dl.free.fr/jP9K5eq4E

**Comment by vpltd-peterm** [comment]
One thing we have discovered, is that Steam only passes on it's controller configuration when you launch the game from BPM. If you launch it from the normal desktop UI, it does not pass this on.

stqn1: I notice that your pad has GUID "03000000250900000500000000010000". This is listed in SDLGamepad.config as "Sony PS2 pad with SmartJoy adapter". This has lefttrigger:b4,righttrigger:b5 - so the triggers are mapped as buttons. You may want to run jstest-gtk and figure out what axes the triggers are mapped as, then try changing this mapping.

**Comment by stqn1** [comment]
Launching the game from big picture mode doesn’t change anything. Also it’s not my experience that it is required for gamepad settings to work in games (but that might be a somewhat recent bug in Steam).
The triggers on PS2 gamepads are simple buttons, not analog.

**Comment by vpltd-peterm** [comment]
Ah of course.. its been a while since I used an actual PS2 pad :)
You can redefine controls inside Dirt itself in this case, but Accelerate/Reverse, the default actions assigned to LT/RT are analog controls. So you would have to remap them to the analog stick for example.

**Comment by grabmateusz** [comment]
In my case running game from Steam Big Picture mode does not fix anything as well (Dualshock 4).

**Comment by stqn1** [comment]
"Accelerate/Reverse, the default actions assigned to LT/RT are analog controls. So you would have to remap them to the analog stick for example."
That doesn’t seem to be the issue, as the lower triggers worked fine with the original version of the game, and I’m able to accelerate and brake with other non-analog buttons in the current version.

**Comment by vpltd-peterm** [comment]
Please test this with BuildID 764084. We fixed a bug where triggers that were digital were not being correctly translated to the equivalent XInput LT/RT controls (which are always analog). Your PS2 pad's triggers should now operate equivalent to fully depressed LT/RT.

**Comment by stqn1** [comment]
Lower triggers are now working fine with my DS2 gamepad :).

**Comment by ProfessorKaos64** [comment]
This is still painful for me on SteamOS. Somehow I got the cursor to go over the onscreen keyboard to input my name.  A black surname still crashed the game for SteamOS brewmaster. This would be a nice game to advertise alongside Steam machines, but this is frustrating. What still happens for me, is when I click A on my wireless MS Xbox controller, the onscreen keyboard shows up to the left, on the right is a text box, and above it is the letter "D", for whatever strange reason. And I have to wonder too, why is there no option to delete profiles from the screen? Is that an overall game limitation?

**Comment by vpltd-peterm** [comment]
The Steam Big Picture onscreen keyboard should be fixed as of BuildID 766171.
The absence of deleting profiles is a feature (!) of the Windows version

**Comment by ProfessorKaos64** [comment]
>The absence of deleting profiles is a feature (!) of the Windows version

Understood. I did start a thread on the community forums for this, but I doubt it will get any attention.

**Comment by vpltd-peterm** [comment]
Can you confirm if the problem with the onscreen keyboard is now fixed?

**Comment by ProfessorKaos64** [comment]
@vpltd-peterm : Now that I have 6 "no name" profiles, I can confirm that it is not fixed. What actually happens, which I can tell by pushing left/right is the overlay is behind the input box/flower-wheel-input. The focus is on that background. The foreground is split 50/50, with the input field on the left, and a text box on the right with the letter "D" above it for some reason. Nothing has seem to change on SteamOS in this area I've had trouble with. I'll continue to test any updates under SteamOS that I notice show up for me.

**Comment by vpltd-kgalaj** [comment]
About Steam overlay: As the same overlay also shows up in in any Linux when Steam Big Picture is used and works correctly there, the difference seems to be in the way Valve's code operates on SteamOS and not in anything the game does, and we don't have control over Valve's code, at present I don't see anything we can do about it.

About deleting profiles: I think it can be done from outside the game. What complicates matters is Steam Cloud, where copies of profiles are stored. What follows is just a suggestion of what should work, as I haven't tried it. Similar recipes for deletion of Steam Cloud resources for other games can be found on Google, they might serve as a guide.

The profiles themselves are in folder ~/.local/share/Steam/userdata/<your Steam ID>/201700/remote folder, each one a set of files starting with savegame@eonprofileX , where X is the profile index (files named savegame@profileX are Windows profiles, not compatible with Mac/Linux ones). But if they're just deleted from there, Steam Cloud will notice and "repair the damage" by replacing them with backups downloaded from Valve's servers, which will undo the deletion. So, try the following:

1. Launch Steam Client,
2. In game's properties, Updates tab, find the checkbox "Enable Steam Cloud Synchronisation for DiRT Showdown" and turn it off.
3. Launch the game (maybe in windowed mode to make switching to other apps easier).
4. Delete the profile you want to delete in remote folder.
5. Exit the game.
6. Turn the "Enable Steam Cloud Synchronisation for DiRT Showdown" back on, and launch the game again. At around this point Steam should notice the discrepancy between the local profile files and online ones, but it won't be able to explain it to itself since it had synchronisation off for a while, so it'll actually ask you whether you want to keep the online version of the files, or the local one. Pick the local one, and information about profile files being deleted should propagate to Cloud.
7. Check if everything works and the profile is actually gone from DiRT.

By the way, the game might be assumming that the profile files are numbered from 0 up, with no gaps between them, so if you delete, say, profile 2, and have profile 3 around, it might be necessary to remanme it to profile 2 for game to spot it.

By the way, when creating new profile in game, you can select old profile to replace with new one, which is useful if you want to test profile creation without increasing profile count.

**Comment by ProfessorKaos64** [comment]
Very nice trick to try with the profiles, I will try that. I had already removed them from the remote/ folder, but of course Steam Cloud returned them. I knew BPM on Linux vs. SteamOS is a big factor, due to SteamOS using it's own compositor, steamcompmgr. If you do ever find a solution for this, let me know, but otherwise I will solider on for the time being.

>By the way, when creating new profile in game, you can select old profile to replace with new one, which is useful if you want to test profile creation without increasing profile count.

I noticed this just yesterday, thank you for the reminder.

**Comment by ProfessorKaos64** [comment]
I was able to delete the profiles, but in the new beta client there is no box to remove the cloud sync option. What I had to do, is go offline, remove the profiles, start the game and create a profile, ignoring online warnings. I exited, restarted Steam in online mode and now I saw the "conflict" status for Steam Cloud.  I chose then to upload my local content over the other option as you said. Though, what also happened, is though my saves looked fine and it appeared to sync, I got a "sync needed" message. [This post](http://forums.steampowered.com/forums/showthread.php?t=2470784) Clued me in that I needed to remove the remote cache vdf file while offline to force the sync. Hopefully this helps SteamOS/beta client folks. 

The input to put in my name was wonky, but I got it by click the name box with the gamepad, moving the mouse to click the empty text box, which kicked me back to the summary screen. I hit enter on a keyboard and was able to type with the keyboard. Crazy, but it worked. Wish there wasn't so much issue around this, but I am now synced, and up and running, racing :)
